apiVersion: v1
kind: Secret
metadata:
  name: podpulse-agent-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "podpulse-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  PODPULSE_API_KEY: {{ .Values.agent.backend.apiKey | required "agent.backend.apiKey is required" | quote }}
  PODPULSE_BACKEND_ADDR: {{ .Values.agent.backend.address | required "agent.backend.address is required" | quote }}